import { RestaurantDefini } from "@/types/price-list";
import Header from "./header";
import { getAllRestaurants } from "@/src/actions/restaurants.actions";
import { Restaurant } from "@/types/models";
import { getRestaurantDefined } from "@/src/price-list/price-list.action";

export const mockRestaurants: RestaurantDefini[] = [
    {
        id: '1',
        idLocation: 'LOC001',
        logo: 'logo1.png',
        logo_Url: 'https://example.com/logo1.png',
        nomEtablissement: 'Le Gourmet',
        longitude: 2.3522,
        latitude: 48.8566,
        typeCommission: 'POURCENTAGE',
        commission: 10,
        position: { longitude: 2.3522, latitude: 48.8566 },
    },
    {
        id: '2',
        idLocation: 'LOC002',
        logo: 'logo2.png',
        logo_Url: 'https://example.com/logo2.png',
        nomEtablissement: 'Chez Pierre',
        longitude: -3.7038,
        latitude: 40.4168,
        typeCommission: 'FIXE',
        commission: 5000,
        position: { longitude: -3.7038, latitude: 40.4168 },
    },
    {
        id: '3',
        idLocation: 'LOC003',
        logo: 'logo3.png',
        logo_Url: 'https://example.com/logo3.png',
        nomEtablissement: 'La Belle Vue',
        longitude: -74.006,
        latitude: 40.7128,
        typeCommission: 'POURCENTAGE',
        commission: 15,
        position: { longitude: -74.006, latitude: 40.7128 },
    },
    {
        id: '4',
        idLocation: 'LOC004',
        logo: 'logo4.png',
        logo_Url: 'https://example.com/logo4.png',
        nomEtablissement: "L'Épicurien",
        longitude: 13.405,
        latitude: 52.52,
        typeCommission: 'FIXE',
        commission: 7000,
        position: { longitude: 13.405, latitude: 52.52 },
    },
    {
        id: '5',
        idLocation: 'LOC005',
        logo: 'logo5.png',
        logo_Url: 'https://example.com/logo5.png',
        nomEtablissement: 'Bistro du Coin',
        longitude: -0.1278,
        latitude: 51.5074,
        typeCommission: 'POURCENTAGE',
        commission: 12,
        position: { longitude: -0.1278, latitude: 51.5074 },
    },
    {
        id: '6',
        idLocation: 'LOC006',
        logo: 'logo6.png',
        logo_Url: 'https://example.com/logo6.png',
        nomEtablissement: 'La Table Royale',
        longitude: 151.2093,
        latitude: -33.8688,
        typeCommission: 'FIXE',
        commission: 6000,
        position: { longitude: 151.2093, latitude: -33.8688 },
    },
    {
        id: '7',
        idLocation: 'LOC007',
        logo: 'logo7.png',
        logo_Url: 'https://example.com/logo7.png',
        nomEtablissement: "Saveurs d'Orient",
        longitude: 37.6173,
        latitude: 55.7558,
        typeCommission: 'POURCENTAGE',
        commission: 8,
        position: { longitude: 37.6173, latitude: 55.7558 },
    },
    {
        id: '8',
        idLocation: 'LOC008',
        logo: 'logo8.png',
        logo_Url: 'https://example.com/logo8.png',
        nomEtablissement: 'Le Petit Marché',
        longitude: -99.1332,
        latitude: 19.4326,
        typeCommission: 'FIXE',
        commission: 4000,
        position: { longitude: -99.1332, latitude: 19.4326 },
    },
    {
        id: '9',
        idLocation: 'LOC009',
        logo: 'logo9.png',
        logo_Url: 'https://example.com/logo9.png',
        nomEtablissement: 'Côté Jardin',
        longitude: 139.6917,
        latitude: 35.6895,
        typeCommission: 'POURCENTAGE',
        commission: 9,
        position: { longitude: 139.6917, latitude: 35.6895 },
    },
    {
        id: '10',
        idLocation: 'LOC010',
        logo: 'logo10.png',
        logo_Url: 'https://example.com/logo10.png',
        nomEtablissement: 'La Dolce Vita',
        longitude: 12.4964,
        latitude: 41.9028,
        typeCommission: 'FIXE',
        commission: 7500,
        position: { longitude: 12.4964, latitude: 41.9028 },
    },
    {
        id: '11',
        idLocation: 'LOC011',
        logo: 'logo11.png',
        logo_Url: 'https://example.com/logo11.png',
        nomEtablissement: "L'Authentique",
        longitude: 174.7762,
        latitude: -41.2865,
        typeCommission: 'POURCENTAGE',
        commission: 14,
        position: { longitude: 174.7762, latitude: -41.2865 },
    },
    {
        id: '12',
        idLocation: 'LOC012',
        logo: 'logo12.png',
        logo_Url: 'https://example.com/logo12.png',
        nomEtablissement: 'Brasserie du Port',
        longitude: -46.6333,
        latitude: -23.5505,
        typeCommission: 'FIXE',
        commission: 5500,
        position: { longitude: -46.6333, latitude: -23.5505 },
    },
    {
        id: '13',
        idLocation: 'LOC013',
        logo: 'logo13.png',
        logo_Url: 'https://example.com/logo13.png',
        nomEtablissement: 'Le Refuge',
        longitude: 18.4241,
        latitude: -33.9249,
        typeCommission: 'POURCENTAGE',
        commission: 11,
        position: { longitude: 18.4241, latitude: -33.9249 },
    },
    {
        id: '14',
        idLocation: 'LOC014',
        logo: 'logo14.png',
        logo_Url: 'https://example.com/logo14.png',
        nomEtablissement: 'La Cabane',
        longitude: 103.8198,
        latitude: 1.3521,
        typeCommission: 'FIXE',
        commission: 9000,
        position: { longitude: 103.8198, latitude: 1.3521 },
    },
    {
        id: '15',
        idLocation: 'LOC015',
        logo: 'logo15.png',
        logo_Url: 'https://example.com/logo15.png',
        nomEtablissement: 'Le Patio',
        longitude: -157.8583,
        latitude: 21.3069,
        typeCommission: 'POURCENTAGE',
        commission: 7,
        position: { longitude: -157.8583, latitude: 21.3069 },
    },
    {
        id: '16',
        idLocation: 'LOC016',
        logo: 'logo16.png',
        logo_Url: 'https://example.com/logo16.png',
        nomEtablissement: 'Le Méditerranéen',
        longitude: 31.2357,
        latitude: 30.0444,
        typeCommission: 'FIXE',
        commission: 6500,
        position: { longitude: 31.2357, latitude: 30.0444 },
    },
    {
        id: '17',
        idLocation: 'LOC017',
        logo: 'logo17.png',
        logo_Url: 'https://example.com/logo17.png',
        nomEtablissement: 'La Cave à Vin',
        longitude: 55.2708,
        latitude: 25.2048,
        typeCommission: 'POURCENTAGE',
        commission: 13,
        position: { longitude: 55.2708, latitude: 25.2048 },
    },
    {
        id: '18',
        idLocation: 'LOC018',
        logo: 'logo18.png',
        logo_Url: 'https://example.com/logo18.png',
        nomEtablissement: 'Le Palais Indien',
        longitude: 77.209,
        latitude: 28.6139,
        typeCommission: 'FIXE',
        commission: 8000,
        position: { longitude: 77.209, latitude: 28.6139 },
    },
];
export default async function SectionHeader(){
// const initialData: RestaurantDefini[] = mockRestaurants;
    const initialData: Restaurant[]|null =  await getAllRestaurants();
    
   
    return <Header initialData={initialData}/>
}